[[VALIDATORS]]
public_key = "nHUHS6rzWd2toxnaCLLcAD6nTLUBKxBsRanjywxLeyZ2q19AmZxe"
attestation = "2E5A9E5E5370B04CD9E8DA3CAA2CCE12635561218D75C5F7EF48699700220CD5B2667DB316B256166257D44AB9880E0CDA241FCAB579F883D897C567E8E8A503"

[[VALIDATORS]]
public_key = "nHUedN7diUp6o3p6H7f6JFSoHfwC3TFjt5YEmrMcwh6p2PYggbpv"
attestation = "63D368401529266C8230988AD545AF8551DFED6F00FFFA2836AF67C2DE83F032C90461DC2A783678F8B6747C892806E8FB2A4775591FFB1D2B1C51F09EA66C01"

[[VALIDATORS]]
public_key = "nHUkbNkhJcPDnSjCuZwqcAiHJUxYvirLJt8Qy38Wyvk6Tri1cq1A"
attestation = "04511C6D72B49BBAC980AF0A1FBC4AD9263DABDBFC8F045B223C8CAD35FA83E151EBEB8ECBBE99A592FC96A90B36CA530669D2FFB572A95F125B489D0E44A509"

[[VALIDATORS]]
public_key = "nHU3VNRD3cBsFwcDcKaMUoikag3RE7PS9p8L4Uj9dYQFv3zsLWdQ"
attestation = "52AD96B548AC71213D487307870440B74EC3A8A7B0DC887A1B936D932E4101782E08C9CCF620F0605021B38A4A42889941F4EFFB18BFB8DA3EF67181FE88C301"

[[VALIDATORS]]
public_key = "nHBiHzPq3iiJ7MxZkZ3LoBBJneRtcZAoXm5Crb985neVN6ygQ3b7"
attestation = "16C9D576875596DE6F77C0BA00B2392CB48FCBF6815DC2F32A4D666D5E0307643E6B1C8107B0839D183474511B428ADB4FB76F37F60BD513627918ED91596402"


