[[VALIDATORS]]
public_key = "nHUHS6rzWd2toxnaCLLcAD6nTLUBKxBsRanjywxLeyZ2q19AmZxe"
attestation = "2E5A9E5E5370B04CD9E8DA3CAA2CCE12635561218D75C5F7EF48699700220CD5B2667DB316B256166257D44AB9880E0CDA241FCAB579F883D897C567E8E8A503"
