[[VALIDATORS]]
public_key = "nHUHS6rzWd2toxnaCLLcAD6nTLUBKxBsRanjywxLeyZ2q19AmZxe"
attestation = "2E5A9E5E5370B04CD9E8DA3CAA2CCE12635561218D75C5F7EF48699700220CD5B2667DB316B256166257D44AB9880E0CDA241FCAB579F883D897C567E8E8A503"

[[VALIDATORS]]
public_key = "nHUedN7diUp6o3p6H7f6JFSoHfwC3TFjt5YEmrMcwh6p2PYggbpv"
attestation = "63D368401529266C8230988AD545AF8551DFED6F00FFFA2836AF67C2DE83F032C90461DC2A783678F8B6747C892806E8FB2A4775591FFB1D2B1C51F09EA66C01"


